version: 2.1


jobs:  
  build-and-test:    
    build: # name of your job
    machine: # executor type
      image: ubuntu-2004:202010-01
    steps:   
      - checkout       
  
      - run:
          name: "Start Services using Docker-Compose"
          command: |
           docker-compose up -d
      - run:
          name: "Check That it’s Running"
          command: |
           docker ps

      - run:
          name: "Test Containers are Accesisable to Check Port Accesibality"
          command: docker exec -it db curl --retry 10 --connect-timeout 30 --retry-delay 5  http://wordpress:80
            
            
            
workflows:  
  build-test-and-deploy:    
    jobs:
      - build-and-test:
          filters:            
            branches:
              only:
                - master
        