version: 2.1


jobs:  
  build-and-test:    
    build: # name of your job
    machine: # executor type
      image: ubuntu-2004:202010-01
    steps:   
      - checkout       
  
      - run:
          name: "Start Service and Check That it’s Running"
          command: |
            docker run -d --name myapi sreedocker123/govstackmccapitestcircleci:latest
              
      - run:
          name: Test API Integration Scripts using Gherkhin and Pytest-BDD
          command: docker exec myapi 
workflows:  
  build-test-and-deploy:    
    jobs:
      - build-and-test:
          filters:            
            branches:
              only:
                - master
        