version: 2.1


jobs:  
  build-and-test:    
    build: # name of your job
    machine: # executor type
      image: ubuntu-2004:202010-01
    steps:   
      - checkout       
  
      - run:
          name: "Start Service and Check That it’s Running"
          command: |
            docker network create cmwd-net
            docker run --network cmwd-net -d -p 8000:8000 --name myapi sreedocker123/govstackmccapitestcircleci:latest
              
      - run:
          name: Test API Integration Scripts using Gherkhin and Pytest-BDD
          command: |
            
            docker run --network cmwd-net  --name test -i -t alpine:3.7 apk add --no-cache curl 
            docker exec -it test --entrypoint /bin/sh curl http://myapi:8000/home/
workflows:  
  build-test-and-deploy:    
    jobs:
      - build-and-test:
          filters:            
            branches:
              only:
                - master
        